# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Probablistic_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Probablistic_Window(object):
    def setupUi(self, Probablistic_Window):
        Probablistic_Window.setObjectName("Probablistic_Window")
        Probablistic_Window.resize(1101, 771)
        self.centralwidget = QtWidgets.QWidget(Probablistic_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.drapdown = QtWidgets.QComboBox(self.centralwidget)
        self.drapdown.setGeometry(QtCore.QRect(50, 80, 271, 31))
        self.drapdown.setCurrentText("")
        self.drapdown.setObjectName("drapdown")
        self.label_Primary = QtWidgets.QLabel(self.centralwidget)
        self.label_Primary.setGeometry(QtCore.QRect(640, 90, 54, 12))
        self.label_Primary.setObjectName("label_Primary")
        self.drapdown_Primary = QtWidgets.QComboBox(self.centralwidget)
        self.drapdown_Primary.setGeometry(QtCore.QRect(730, 80, 351, 31))
        self.drapdown_Primary.setCurrentText("")
        self.drapdown_Primary.setMinimumContentsLength(0)
        self.drapdown_Primary.setObjectName("drapdown_Primary")
        self.Map_view = QtWidgets.QFrame(self.centralwidget)
        self.Map_view.setGeometry(QtCore.QRect(30, 120, 601, 561))
        font = QtGui.QFont()
        font.setBold(False)
        self.Map_view.setFont(font)
        self.Map_view.setFrameShape(QtWidgets.QFrame.Box)
        self.Map_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Map_view.setObjectName("Map_view")
        self.imglabel = QtWidgets.QLabel(self.Map_view)
        self.imglabel.setGeometry(QtCore.QRect(0, 0, 601, 561))
        self.imglabel.setObjectName("imglabel")
        self.Graph_view = QtWidgets.QFrame(self.centralwidget)
        self.Graph_view.setGeometry(QtCore.QRect(640, 170, 441, 281))
        font = QtGui.QFont()
        font.setBold(False)
        self.Graph_view.setFont(font)
        self.Graph_view.setFrameShape(QtWidgets.QFrame.Box)
        self.Graph_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Graph_view.setObjectName("Graph_view")
        self.graph_label = QtWidgets.QLabel(self.Graph_view)
        self.graph_label.setGeometry(QtCore.QRect(0, 0, 441, 281))
        self.graph_label.setObjectName("graph_label")
        self.Map_properties = QtWidgets.QFrame(self.centralwidget)
        self.Map_properties.setGeometry(QtCore.QRect(640, 460, 441, 221))
        font = QtGui.QFont()
        font.setBold(False)
        self.Map_properties.setFont(font)
        self.Map_properties.setFrameShape(QtWidgets.QFrame.Box)
        self.Map_properties.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Map_properties.setObjectName("Map_properties")
        self.tabWidget = QtWidgets.QTabWidget(self.Map_properties)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 441, 221))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.map_propery_label = QtWidgets.QLabel(self.tab)
        self.map_propery_label.setGeometry(QtCore.QRect(0, 0, 431, 191))
        self.map_propery_label.setObjectName("map_propery_label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Graph_propery_label = QtWidgets.QLabel(self.tab_2)
        self.Graph_propery_label.setGeometry(QtCore.QRect(0, 0, 431, 221))
        self.Graph_propery_label.setObjectName("Graph_propery_label")
        self.tabWidget.addTab(self.tab_2, "")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(410, 20, 261, 41))
        self.textEdit.setObjectName("textEdit")
        self.label_Secondary = QtWidgets.QLabel(self.centralwidget)
        self.label_Secondary.setGeometry(QtCore.QRect(640, 130, 71, 16))
        self.label_Secondary.setObjectName("label_Secondary")
        self.drapdown_Secondary = QtWidgets.QComboBox(self.centralwidget)
        self.drapdown_Secondary.setGeometry(QtCore.QRect(730, 120, 351, 31))
        self.drapdown_Secondary.setCurrentText("")
        self.drapdown_Secondary.setMinimumContentsLength(0)
        self.drapdown_Secondary.setObjectName("drapdown_Secondary")
        Probablistic_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Probablistic_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 22))
        self.menubar.setObjectName("menubar")
        Probablistic_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Probablistic_Window)
        self.statusbar.setObjectName("statusbar")
        Probablistic_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Probablistic_Window)
        self.drapdown.setCurrentIndex(-1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Probablistic_Window)

    def retranslateUi(self, Probablistic_Window):
        _translate = QtCore.QCoreApplication.translate
        Probablistic_Window.setWindowTitle(_translate("Probablistic_Window", "MainWindow"))
        self.label_Primary.setText(_translate("Probablistic_Window", "Primary"))
        self.imglabel.setText(_translate("Probablistic_Window", "TextLabel"))
        self.graph_label.setText(_translate("Probablistic_Window", "TextLabel"))
        self.map_propery_label.setText(_translate("Probablistic_Window", "The map drawing is supported by GeoPandas."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Probablistic_Window", "Map Propery"))
        self.Graph_propery_label.setText(_translate("Probablistic_Window", "The Graph plotting is supported by pandas."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Probablistic_Window", "Graph Property"))
        self.textEdit.setHtml(_translate("Probablistic_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Probablistic Single Page</span></p></body></html>"))
        self.label_Secondary.setText(_translate("Probablistic_Window", "Secondary"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Probablistic_Window = QtWidgets.QMainWindow()
    ui = Ui_Probablistic_Window()
    ui.setupUi(Probablistic_Window)
    Probablistic_Window.show()
    sys.exit(app.exec_())
